import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const faqs = [
  // 1. Account & Login
  { question: "How do I log in to the Associate Partner Portal?", answer: "Open the Associate Partner Portal login page and enter your system-generated Associate ID and password. The portal uses the Associate ID as the primary login identifier.", category: "Account & Login" },
  { question: "What is my Associate ID?", answer: "Your Associate ID is a unique ID generated by the system when your account is created. Associate IDs follow the configured role-based format. Associates use ASSOC-RS-####, Associate Managers use ASSOC-MN-####, and MD accounts use ASSOC-MD-####.", category: "Account & Login" },
  { question: "Can I change my Associate ID?", answer: "No. The Associate ID is generated by the system and is a read-only official identifier. It cannot be changed from the profile or account settings.", category: "Account & Login" },
  { question: "What should I do if I enter the wrong password?", answer: "Check your Associate ID and password and try again. If you still cannot sign in, contact the authorized management person responsible for your account.", category: "Account & Login" },
  { question: "What happens when I receive a temporary password?", answer: "A temporary password is used for initial account access where applicable. The portal can require a password change during the first login so that the temporary password is replaced with your own secure password.", category: "Account & Login" },
  { question: "How do I change my password?", answer: "Open My Profile and go to the Security section. Enter your current password, new password, and confirmation password, then save the change.", category: "Account & Login" },
  { question: "Can I use my email address to log in?", answer: "The portal's primary login credential is the system-generated Associate ID and password.", category: "Account & Login" },
  
  // 2. Dashboard
  { question: "What can I see on my Dashboard?", answer: "Your Dashboard provides a summary of your portal activity, including the main navigation, promotional carousel, key performance figures, featured projects, active offers, quick actions, and other relevant operational information available to your role.", category: "Dashboard" },
  { question: "What do the Dashboard KPI cards show?", answer: "KPI cards summarize important activity such as team information, bookings, commission, site visits, and other configured performance metrics.", category: "Dashboard" },
  { question: "Why do I not see a particular Dashboard section?", answer: "Dashboard content is controlled by your role, permissions, available data, and active business content. Some sections may only appear when applicable information is available.", category: "Dashboard" },
  
  // 3. Projects
  { question: "How do I view projects?", answer: "Open Projects from the main navigation. You can review project information, available inventory, layouts, pricing, media, offers, and other project details that your role is permitted to view.", category: "Projects" },
  { question: "What does the Verified project badge mean?", answer: "A Verified badge indicates that the project has passed the required management approval process. The badge must come from the authorized backend workflow and cannot be manually assigned by an Associate.", category: "Projects" },
  { question: "Can Associates create or approve projects?", answer: "Project creation and management follow the configured role permissions. Associates are not allowed to bypass the project's approval workflow, and only authorized management roles can perform management actions.", category: "Projects" },
  { question: "What information is available for a project?", answer: "Project information can include basic details, location, legal information, land details, inventory, pricing, payment plans, amenities, nearby infrastructure, construction details, marketing information, media, sales information, project FAQs, and layouts where available.", category: "Projects" },
  
  // 4. Inventory & Layout
  { question: "What is the Project Layout?", answer: "The Project Layout is the visual representation of the project's plots, units, blocks, floors, or other property inventory. It helps you understand where each inventory item is located and what its current availability status is.", category: "Inventory & Layout" },
  { question: "Can different projects have different layouts and numbering?", answer: "Yes. Each project can have its own layout design, block structure, floor sequence, plot numbers, unit numbers, and numbering system. The portal does not require every project to use the same numbering pattern.", category: "Inventory & Layout" },
  { question: "What do the inventory statuses mean?", answer: "Available or Vacant means the property can be considered for booking according to the current rules. Reserved means it is temporarily held. Booked means a booking has been recorded. Registered means the property has reached the configured registered state. Sold indicates it is no longer available for booking. Exact statuses depend on the project's configured workflow.", category: "Inventory & Layout" },
  { question: "Can I book a unit that is already booked or registered?", answer: "No. Inventory availability is controlled by the backend. A unit that is no longer available cannot be confirmed for a new booking.", category: "Inventory & Layout" },
  { question: "Can I see the layout on mobile?", answer: "Yes. The layout viewer is designed to adapt to mobile screens. Where necessary, the layout itself may use controlled internal scrolling so that the entire application page does not overflow horizontally.", category: "Inventory & Layout" },

  // 5. Bookings
  { question: "How do I create a booking?", answer: "Open Bookings and start a new booking. Select the eligible project and available inventory, enter the customer details and booking information, review the details, and submit the booking through the configured workflow.", category: "Bookings" },
  { question: "Can I book an unavailable unit?", answer: "No. The backend checks inventory availability and prevents unauthorized or conflicting bookings.", category: "Bookings" },
  { question: "What happens after I submit a booking?", answer: "The booking enters the configured review and verification workflow. The status can change as authorized team members process the booking.", category: "Bookings" },
  { question: "Can two Associates book the same unit at the same time?", answer: "The system is designed to protect inventory against conflicting confirmations using backend validation and transaction/concurrency controls.", category: "Bookings" },
  { question: "Where can I see my bookings?", answer: "Open Bookings from the main navigation. You can view the bookings that your role is authorized to access.", category: "Bookings" },

  // 6. Commission
  { question: "Where can I see my commission?", answer: "Open Commission from the main navigation. The Commission section can show total commission, received commission, pending amounts, and the detailed commission ledger.", category: "Commission" },
  { question: "What currency is used in the portal?", answer: "The portal operates in India, so financial values are displayed in Indian Rupees using the ₹ symbol and Indian number formatting.", category: "Commission" },
  { question: "How is commission calculated?", answer: "Commission is calculated according to the commission rules configured for the applicable Associate, project, transaction, or business condition. The underlying calculation is controlled by the portal's backend.", category: "Commission" },
  { question: "Can I change commission rules?", answer: "No. Commission configuration is controlled by authorized management roles according to the portal's permission model.", category: "Commission" },
  { question: "Why is my commission showing as pending?", answer: "A commission can remain pending until the related booking or payment workflow reaches the required business state.", category: "Commission" },

  // 7. Team
  { question: "What can I see in Team?", answer: "Team shows the Associates and hierarchy information available to your role. It can include team members, reporting relationships, bookings, site visits, commission performance, and other permitted team information.", category: "Team" },
  { question: "Can Associates see everyone in the organization?", answer: "No. Associate visibility follows the server-side hierarchy rules. An Associate can see their permitted team/downline rather than unrelated upline or parallel branches.", category: "Team" },
  { question: "Can MD and Associate Managers view Associates?", answer: "MD has organization-wide visibility according to their authority. Associate Manager visibility follows the configured management scope and portal rules.", category: "Team" },
  { question: "Can I see another Associate's bank details or Aadhaar?", answer: "No. Sensitive information such as Aadhaar, PAN, bank details, private address, and emergency information is protected and is not exposed through ordinary team visibility.", category: "Team" },

  // 8. Travel Allowance
  { question: "How do I request Travel Allowance?", answer: "Open Travel Allowance, create a new request, enter the travel date, route, purpose, project/customer information where applicable, distance, travel mode, amount requested, and supporting information, then submit according to the workflow.", category: "Travel Allowance" },
  { question: "Can I upload a travel bill?", answer: "Yes. The portal supports the configured supporting-document upload flow for Travel Allowance.", category: "Travel Allowance" },
  { question: "What is the Travel Allowance approval process?", answer: "The normal workflow is PENDING → MD REVIEW → APPROVED or REJECTED → PAID.", category: "Travel Allowance" },
  { question: "Where can I see a rejected Travel Allowance reason?", answer: "Open the relevant Travel Allowance request details. The rejection reason is retained with the request when the request is rejected.", category: "Travel Allowance" },

  // 9. Site Visits
  { question: "How do I schedule a Site Visit?", answer: "Open Site Visits, create a new visit, select the project, enter the customer information, choose the date and time, add remarks if needed, and save the visit.", category: "Site Visits" },
  { question: "What Site Visit statuses are available?", answer: "The portal can track stages such as Scheduled, On the Way, Arrived, Customer Met, Completed, Cancelled, and Rescheduled according to the configured workflow.", category: "Site Visits" },
  { question: "What should I enter when a Site Visit is completed?", answer: "Complete the visit outcome information and provide the required remarks/follow-up details according to the form.", category: "Site Visits" },
  { question: "Can I see team Site Visits?", answer: "Visibility depends on your role and hierarchy permissions. Management users may have wider operational visibility than Associates.", category: "Site Visits" },

  // 10. Offers
  { question: "Where can I see current offers?", answer: "Offers can appear on the Dashboard and in the Offers section. Only eligible active/scheduled offers should be shown according to the configured rules.", category: "Offers" },
  { question: "What information is shown for an offer?", answer: "An offer may include the offer title, description, project, validity period, reward, target bookings, achieved bookings, progress, and current status.", category: "Offers" },
  { question: "How is offer progress calculated?", answer: "Where booking-based achievement is configured, progress is calculated from the applicable verified booking data rather than from manually entered fake progress values.", category: "Offers" },
  { question: "Will I be notified about a new offer?", answer: "Eligible active Associates can receive a notification when a new active offer is published according to the portal's notification rules.", category: "Offers" },

  // 11. Reviews
  { question: "How do I request a customer review?", answer: "Open Reviews, select an eligible booking, and create a review request. The system generates a secure review link that can be shared with the customer.", category: "Reviews" },
  { question: "Can a customer submit more than one review through the same link?", answer: "No. Once a review request has been submitted, the review becomes immutable and cannot be submitted again through the same request.", category: "Reviews" },
  { question: "Can an Associate edit a submitted customer review?", answer: "No. Submitted customer reviews are immutable and cannot be edited by Associates, AMs, or MDs.", category: "Reviews" },
  { question: "What does Review Analytics show?", answer: "Review Analytics can include total reviews, average rating, bookings, site visits, conversion, and commission-related performance where available.", category: "Reviews" },

  // 12. Notifications
  { question: "Where can I see notifications?", answer: "Use the notification bell in the application header or open the Notifications page for the complete notification list.", category: "Notifications" },
  { question: "Can I mark notifications as read?", answer: "Yes. You can mark individual notifications as read and use the Mark All as Read action where available.", category: "Notifications" },
  { question: "What kinds of notifications can I receive?", answer: "Notifications can relate to Booking, Project, Commission, Travel, Team, Approval, Offer, Site Visit, Review, and System events.", category: "Notifications" },
  { question: "Will I receive a notification for every project created?", answer: "Notifications are generated according to the configured project publishing and visibility workflow. Draft-only changes should not normally notify Associates before the project becomes available to them.", category: "Notifications" },

  // 13. My Profile
  { question: "What information is available in My Profile?", answer: "My Profile can include personal information, employment details, profile photo, security settings, emergency contact information, financial information according to permissions, and other account-related information.", category: "My Profile" },
  { question: "Can I change my Associate ID?", answer: "No. The Associate ID is system-generated and read-only.", category: "My Profile" },
  { question: "Can I change my profile photo?", answer: "Yes. Use the profile photo control in My Profile to upload or replace your photo, subject to the portal's image validation rules.", category: "My Profile" },
  { question: "How do I change my password?", answer: "Open My Profile → Security, enter your current password, create a new password, confirm it, and save.", category: "My Profile" },

  // 14. PWA / Install App
  { question: "Can I install the portal as an app?", answer: "Yes. The portal is designed as an installable PWA. Open My Profile and use the Install App option when your browser provides native installation support.", category: "PWA / Install App" },
  { question: "What happens when the app is already installed?", answer: "The profile page should show the installed state rather than repeatedly asking you to install the app.", category: "PWA / Install App" },
  { question: "Why might I see browser installation instructions instead of an Install prompt?", answer: "Native installation behavior depends on the browser and whether the application currently meets the browser's installability conditions. The portal should use the native install prompt when supported and show appropriate fallback guidance when it is not.", category: "PWA / Install App" },

  // 15. Security
  { question: "Why are some Associate details hidden?", answer: "Sensitive information is protected for security and privacy. Team visibility does not automatically expose Aadhaar, PAN, bank details, private address, emergency information, or other protected fields.", category: "Security" },
  { question: "Can I see another Associate's private information?", answer: "No. The portal uses backend authorization and hierarchy rules to control what each role can access.", category: "Security" },
  { question: "Can I approve my own request?", answer: "No. The approval workflow prevents users from bypassing the required authorization process, including self-approval where applicable.", category: "Security" },
  { question: "Why was my second MD or AM login blocked?", answer: "MD and Associate Manager accounts can be configured for one active device/session at a time. A second login can therefore be rejected according to the session policy.", category: "Security" },

  // 16. Approvals & Requests
  { question: "What are Pending Requests?", answer: "Pending Requests show requests that are waiting for review or action according to the user's role and the relevant business workflow.", category: "Approvals & Requests" },
  { question: "What is Pending Authorization?", answer: "Pending Authorization is the MD's centralized area for requests that require final management action across configured modules.", category: "Approvals & Requests" },
  { question: "What are Commission Requests?", answer: "Commission Requests are commission-related requests requiring the appropriate review/authorization. The underlying commission configuration is controlled by authorized management.", category: "Approvals & Requests" },
  { question: "Does every Associate creation require MD approval?", answer: "Not necessarily. When MD directly creates an Associate, the account follows the direct-creation workflow and does not require an additional approval from MD. Associates or other authorized roles referring/creating an Associate may follow the configured approval workflow before the account becomes active.", category: "Approvals & Requests" },

  // 17. General Portal Usage
  { question: "Why do some pages or buttons differ by role?", answer: "The Associate Partner Portal is role-based. MD, Associate Manager, and Associate users have different permissions and operational responsibilities, so the interface and available actions can vary.", category: "General Portal Usage" },
  { question: "Why can I view something but not edit it?", answer: "Viewing and modification are controlled separately by backend permissions. Some information is intentionally read-only for certain roles.", category: "General Portal Usage" },
  { question: "What should I do if a page shows an error?", answer: "Refresh the page and retry once. If the problem continues, record the page name and the exact error message and report it to the authorized portal administrator.", category: "General Portal Usage" },
  { question: "Is the portal available on mobile?", answer: "Yes. The portal is designed as a responsive web application and installable PWA, with layouts adapted for desktop, tablet, and mobile screens.", category: "General Portal Usage" }
];

const categoryOrder = [
  "Account & Login",
  "Dashboard",
  "Projects",
  "Inventory & Layout",
  "Bookings",
  "Commission",
  "Team",
  "Travel Allowance",
  "Site Visits",
  "Offers",
  "Reviews",
  "Notifications",
  "My Profile",
  "PWA / Install App",
  "Security",
  "Approvals & Requests",
  "General Portal Usage"
];

async function seed() {
  console.log('Seeding FAQs...');

  // Delete existing FAQs to prevent duplicates
  await prisma.faq.deleteMany({});
  
  let order = 0;
  
  for (const cat of categoryOrder) {
    const categoryFaqs = faqs.filter(f => f.category === cat);
    
    for (const faq of categoryFaqs) {
      order += 10;
      
      // Default to all roles
      let roles = ['MD', 'ASSOCIATE_MANAGER', 'ASSOCIATE'];
      
      // Make "Approvals & Requests" MD and AM only
      if (cat === "Approvals & Requests") {
        roles = ['MD', 'ASSOCIATE_MANAGER'];
      }
      
      // Make the specific MD/AM blocked login question AM/MD only
      if (faq.question === "Why was my second MD or AM login blocked?") {
        roles = ['MD', 'ASSOCIATE_MANAGER'];
      }
      
      await prisma.faq.create({
        data: {
          question: faq.question,
          answer: faq.answer,
          category: faq.category,
          roleVisibility: roles,
          isPublished: true,
          displayOrder: order
        }
      });
    }
  }
  
  const count = await prisma.faq.count();
  console.log(`Successfully seeded ${count} FAQs.`);
}

seed()
  .catch(e => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
